//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIC_School
    {
        public string ID { get; set; }
        public string SchoolCode { get; set; }
        public string SchoolName { get; set; }
        public string LogoImg { get; set; }
        public string SchoolEmail { get; set; }
        public string SchoolFax { get; set; }
        public string SchoolTel { get; set; }
        public string Linkman { get; set; }
        public string AddressCode { get; set; }
        public string Address { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
