//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIC_Class
    {
        public string ID { get; set; }
        public string ClassName { get; set; }
        public string ClassTeacher { get; set; }
        public string SchoolID { get; set; }
        public string YearPeriodID { get; set; }
        public string ClassRoomID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public Nullable<int> QYclassID { get; set; }
        public string ClassIcon { get; set; }
    }
}
