//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIC_Student
    {
        public string ID { get; set; }
        public string SchoolID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string HeadImage { get; set; }
        public string ClassID { get; set; }
        public Nullable<int> SeatNumber { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string StudentNumber { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public Nullable<short> IsAysncToRx { get; set; }
        public string QYUserId { get; set; }
        public string WeChat { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> IsCheckIn { get; set; }
    }
}
